language: python

sudo: false

cache:
  pip: true
  directories:
  - $HOME/.m2
  - $HOME/.cache/bower/

python:
  - "3.4"
  - "3.5"

env:
    # the Django version from requirements.txt is used
  - $DENV=""
    # the latest Django stable version is used
  - $DENV="pip install --upgrade Django"
    # the latest Django development version is used
  - $DENV="pip install --upgrade --pre Django"

install:
  - pip install -r requirements.txt
  - $DENV
  - django-admin --version
  - pip install coveralls
  - npm install -g bower
  - bower install

before_script:
# @see https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# command to run tests
script:
  - export PYTHONWARNINGS=all
  - python manage.py check 
  - python manage.py test 
  - coverage run --omit="*/migrations*" --source="." manage.py test

after_success:
  coveralls

addons:
    code_climate:
        repo_token: 5eba139571641c629d395a5f9bec56f9cbc655ce23579c6febdede10c490c6ce
