language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO=1.9
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script: python manage.py test
